config/routes.rb
Rails.application.routes.draw do

  resources :restaurants do
    resources :reviews
  end

  resources :main
  
  devise_for :users

  root 'main#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_attached_file :image, :default_url => "https://static1.squarespace.com/static/545d5371e4b079130f435921/545d648fe4b00403fdd1b08c/54658cb9e4b0bc178ac9d855/1415941312846/_DLR5185.jpg"
  validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]
  validates :name, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :user, presence: true

  has_many :reviews, dependent: :destroy
  belongs_to :user


  def get_reviews(restaurant_id)
    Review.where(restaurant_id: restaurant_id)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  validates :restaurant, presence: true
  belongs_to :user
  validates :user, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :restaurants, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  def self.create_review(restaurant, currentUser, review_params)
    review = restaurant.reviews.create(review_params)
    review.user_id = currentUser
    review.save
  end

  def has_already_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def new
    if !user_signed_in?
      redirect_to '/restaurants'
    end
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user_id = current_user.id
    @restaurant.save
    redirect_to '/restaurants'
  end

  def account
    @restaurants = Restaurant.where(user_id: current_user.id)
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes!(restaurant_params)
      flash[:notice] = "Your restaurant has been updated."
      redirect_to '/restaurants'
    else
      flash[:notice] = "Your restaurant failed to update. Please try again."
      redirect_to '/restaurants'
    end
  end

  def delete
    @restaurant = Restaurant.find(params[:id])
  end

  def destroy
    @restaurant = Restaurant.find(params[:id]).destroy
    # flash[:notice] = "This restaurant has been deleted."
    redirect_to '/restaurants'
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :location, :image)
  end

end

app/controllers/review_controller.rb
class ReviewController < ApplicationController
  before_action do
    @currentUser = current_user.id
  end

  def new
    @id = params[:restaurant]

  end

  def create
      @restaurant = Restaurant.find_by_id(params[:review][:id])
      if current_user.has_already_reviewed? @restaurant
        flash[:notice]='Have you left a review before? Just stop.'
        redirect_to '/restaurants/all'
      elsif @currentUser == @restaurant.user_id
        flash[:notice]='Is this your own restaurant? You cannot do that.'
        redirect_to '/restaurants/all'
      else
        User.create_review(@restaurant, @currentUser, review_params)
        redirect_to '/restaurants/all'
     end
  end

  private
  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action do
    @currentUser = current_user.id
  end

  def new
    @id = params[:restaurant_id]
  end

  def create
    @restaurant = Restaurant.find_by_id(params[:review][:id])
    if current_user.has_already_reviewed? @restaurant
      flash[:notice]='Have you left a review before? Just stop.'
      redirect_to '/restaurants'
    elsif @currentUser == @restaurant.user_id
      flash[:notice]='Is this your own restaurant? You cannot do that.'
      redirect_to '/restaurants'
    else
      User.create_review(@restaurant, @currentUser, review_params)
      redirect_to '/restaurants'
    end
  end

  private
  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MakerYelp</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<ul class="hmenu">
 <%= render 'devise/menu/registration_items' %>
 <%= render 'devise/menu/login_items' %>

</ul>
<style>
  .notice, .alert {
    padding: 0px;
    margin :0px;
  }
  .jumbotron {
    margin-top: 50px;
    background-color: #ff7977;
    color: white;
  }
</style>

<%= yield %>

</body>
</html>

app/views/main/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body class="home">
    <form class="wrapper" action="/restaurants/all">
      <input class="button" type="submit" value="MakerYelp">
    </form>
  </body>
</html>

app/views/main/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body class="home">
    <form class="wrapper" action="/restaurants">
      <input class="button" type="submit" value="Enter">
    </form>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container" style="padding: 100px 400px 0px 400px;">
<%= form_for :restaurant, url: { action: "create"}, :html => { :multipart => true } do |form| %>
  <p>Name</p>
  <%= form.text_field :name, class: 'form-control', placeholder: 'Name'%>
  <p>Location</p>
  <%= form.text_field :location, class: 'form-control', placeholder: 'Location' %><br><br>
  <p>Description</p>
  <%= form.text_area :description, class: 'form-control', placeholder: 'Description' %><br><br>
  <p>Image</p>
  <%= form.file_field :image %>
  <%= form.button "Save", class: 'btn btn-lg btn-primary btn-block' %>
<% end %>

</div>

app/views/restaurants/all.html.erb
<div class="jumbotron text-center">
  <h1 class="headings"> Your Local Restaurants </h1>
</div>
<div class="container">
  <% @restaurants.each do |restaurant| %>
  <div class="restaurants">
    <div class="row">
      <div class="col-xs-3">
        <img src="<%=restaurant.image%>" height="150" width="200"></img>
      </div>
      <div class="col-xs-4">
        <h2> <%= restaurant.name %> </h2>
        <% average_rating = 0 %>
        <% if restaurant.reviews.length != 0  %>
        <% restaurant.reviews.each do |review| %>
        <% average_rating += review.rating  %>
        <% end %>
        <% average_rating = average_rating/restaurant.reviews.length%>
        <% end %>
        <p> <%= "⭐️" * average_rating %> </p>
        <p> <%= restaurant.description %> </p>
        <p> <%= restaurant.location %> </p>
        <%= link_to "Write Review", new_review_path(restaurant)%>
      </div>
      <div class="col-xs-4">
        <h3>Reviews</h3>
        <% reviews = restaurant.get_reviews(restaurant.id) %>
        <% reviews.last(3).each do |review| %>
        <%= User.find_by_id(review.user_id).email%> wrote:
        <%= "⭐️" * review.rating %>
        <%= review.comment %><br>
        <% end %>
      </div>
    </div><br>
    <hr>
  </div>

  <% end %>
</div>
<style>
h2, h3 {
  padding: 0px;
  margin-top: 0px;
}
hr {    display: block;
  margin-top: 0.5em;
  margin-bottom: 0.5em;
  margin-left: auto;
  margin-right: auto;
  border-style: inset;
  border-width: 1px;}
  </style>

app/views/restaurants/delete.html.erb
<!-- <%= link_to("Back to My Account page", {action: 'account'}, class: 'back-link') %>

<div class="restaurant delete">
  <h2> Delete <%= @restaurant.name %> </h2>

  <%= form_for(:restaurant, url: {action: 'delete', id: @restaurant.id}) do |r|%>

  <p>Are you sure you want to permanently delete <%= @restaurant.name %> ? </p>

<div class="form-buttons">
    <%= submit_tag("Delete this restaurant") %>
  </div>
  <%end%>
</div> -->

app/views/restaurants/edit.html.erb
<h1>Edit <%=@restaurant.name%></h1>

<%=form_for(@restaurant, url: {action: 'update', id: @restaurant.id}, :html => { :multipart => true }) do |r| %>
<h2 style="margin-left:45%;">Edit <%=@restaurant.name%></h2>
<%= render(partial: "form", locals: {r: r}) %>
<%end%>

app/views/restaurants/index.html.erb
<div class="jumbotron text-center">
  <h1 class="headings"> Your Local Restaurants </h1>
</div>
<% if user_signed_in?%>
<p style="margin-left: 1200px;"> <%= link_to "Add new restaurant", new_restaurant_path%></p>
<% end %>
<div class="container">
  <% @restaurants.each do |restaurant| %>
  <div class="restaurants">
    <div class="row">
      <div class="col-xs-3">
        <img src="<%=restaurant.image%>" height="150" width="200"></img>
      </div>
      <div class="col-xs-4">
        <h2> <%= restaurant.name %> </h2>
        <% average_rating = 0 %>
        <% if restaurant.reviews.length != 0  %>
        <% restaurant.reviews.each do |review| %>
        <% average_rating += review.rating  %>
        <% end %>
        <% average_rating = average_rating/restaurant.reviews.length%>
        <% end %>
        <p> <%= "⭐️" * average_rating %> </p>
        <p> <%= restaurant.description %> </p>
        <p> <%= restaurant.location %> </p>
        <p> <%= link_to "Write Review", new_restaurant_review_path(restaurant)%>
        <% if user_signed_in? && restaurant.user_id == current_user.id %>
        <%= link_to "Edit", edit_restaurant_path(restaurant)%>
        <%= link_to("Delete", restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure?' }) %>
        <% end %>
        </p>
      </div>
      <div class="col-xs-4">
        <h3>Reviews</h3>
        <% reviews = restaurant.get_reviews(restaurant.id) %>
        <% reviews.last(3).each do |review| %>
        <%= User.find_by_id(review.user_id).email%> wrote:
        <%= "⭐️" * review.rating %>
        <%= review.comment %><br>
        <% end %>
      </div>
    </div><br>
    <hr>
  </div>
  <% end %>
</div>
<style>
h2, h3 {
  padding: 0px;
  margin-top: 0px;
}
hr {    display: block;
  margin-top: 0.5em;
  margin-bottom: 0.5em;
  margin-left: auto;
  margin-right: auto;
  border-style: inset;
  border-width: 1px;}
  </style>

app/views/restaurants/new.html.erb
<%= form_for :restaurant, url: {action: "create"}, html: {class: "new_restaurant", multipart: true} do |r| %>
<h2 style="margin-left:40%;">Add Restaurant</h2>
<%= render(partial: "form", locals: {r: r}) %>
<% end %>

app/views/reviews/new.html.erb
<div class="container" style="padding: 100px 400px 0px 400px;">
<%= form_for :review, url: {action: "create"}, html: {class: "new_review"} do |r| %>
<h2 class="form-signin-heading">Write Your Review</h2>
  <%= r.hidden_field :id, :value => @id  %>
  <%= r.number_field :rating, min:1, max: 5 , class: 'form-control', placeholder: 'Rating'%><br><br>
  <%= r.text_field :comment, class: 'form-control', placeholder: 'Comment'%><br><br>
 <%= r.file_field :image, class: 'form-control', placeholder: 'Image'%><br><br>
 <%= r.button "Save", class: 'btn btn-lg btn-primary btn-block' %>
<% end %>
</div>